name: binder_env
channels:
- conda-forge
dependencies:
- python=3.9.16
- pip
- pip:
  - tensorflow==2.10.1
  - keras==2.10.0
  - tensorflow-probability==0.17.0
  - pandas==1.5.3
  - numpy==1.24.3
  - scikit-learn==1.2.2
  - matplotlib==3.7.1
  - matplotlib-inline==0.1.6
  - seaborn==0.12.2
  - scipy==1.9.1
  - loguru==0.7.0
  - lime==0.2.0.1
  - alibi==0.9.1
  - git+https://github.com/MaximeJumelle/ALEPython.git@dev#egg=alepython
  - protobuf==3.19.6
